// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCowUHkdc7oRFsxVHkrM2JWfP9iVxemAqQ',
    appId: '1:918048015551:web:a3f5f7169cbf9632df720a',
    messagingSenderId: '918048015551',
    projectId: 'advancefluttercourse',
    authDomain: 'advancefluttercourse.firebaseapp.com',
    storageBucket: 'advancefluttercourse.appspot.com',
    measurementId: 'G-QTQGG5WM54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9lb28M3iVrON-xes7thQ2QfovkWFtRB8',
    appId: '1:918048015551:android:a6c86380ffc93e37df720a',
    messagingSenderId: '918048015551',
    projectId: 'advancefluttercourse',
    storageBucket: 'advancefluttercourse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvCyIPeOuQdN4TrTBufGEX0dAmLAswigo',
    appId: '1:918048015551:ios:6b89774ea2ae3ef3df720a',
    messagingSenderId: '918048015551',
    projectId: 'advancefluttercourse',
    storageBucket: 'advancefluttercourse.appspot.com',
    iosBundleId: 'com.example.advanceFlutterCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvCyIPeOuQdN4TrTBufGEX0dAmLAswigo',
    appId: '1:918048015551:ios:bbf09120b75455d0df720a',
    messagingSenderId: '918048015551',
    projectId: 'advancefluttercourse',
    storageBucket: 'advancefluttercourse.appspot.com',
    iosBundleId: 'com.example.advanceFlutterCourse.RunnerTests',
  );
}
